active_config: default
configs:
  at:
    aiming:
      falloff_correction:
        amount: 1.0069999999999997
        decrease_key: SUBTRACT
        increase_key: ADD
      fixed_correction:
        amount: 0
        decrease_key: NUMPAD9
        increase_key: NUMPAD6
      locations:
        - Head
        - HeadEnd
        - Spine
        - Spine1
        - Spine2
        - Neck
        - Neck1
        - RightShoulder
        - RightArm
        - RightForeArm
        - RightHand
        - LeftShoulder
        - LeftArm
        - LeftForeArm
        - LeftHand
        - Hips
      movement_prediction_factor:
        amount: 0.03
        decrease_key: PAGEDOWN
        increase_key: PAGEUP
        is_active: true
        toggle_key: MULTIPLY
      switch_location_key: END
    auto_scope:
      is_active: false
    auto_shoot:
      is_active: false
      toggle_key: NUMPAD1
    basic:
      fov: 3
      hold_to_aim_key: ALT
      min_distance: null
      screen_size:
        height: 1080
        width: 1920
      toggle_keep_target: NUMPAD3
    dodge:
      crouch_Key: ctrl
      is_active: false
      toggle_key: NUMPAD2
    hunt:
      target_select: NUMPAD8
      toggle_key: NUMPAD5
  default:
    aiming:
      falloff_correction:
        amount: 1.005
        decrease_key: SUBTRACT
        increase_key: ADD
      fixed_correction:
        amount: 1
        decrease_key: NUMPAD9
        increase_key: NUMPAD6
      locations:
        - Head
        - HeadEnd
        - Spine
        - Spine1
        - Spine2
        - Neck
        - Neck1
        - RightShoulder
        - RightArm
        - RightForeArm
        - RightHand
        - LeftShoulder
        - LeftArm
        - LeftForeArm
        - LeftHand
        - Hips
      movement_prediction_factor:
        amount: 0.025
        decrease_key: PAGEDOWN
        increase_key: PAGEUP
        is_active: false
        toggle_key: MULTIPLY
      switch_location_key: END
    auto_scope:
      is_active: false
    auto_shoot:
      is_active: false
      toggle_key: NUMPAD1
    basic:
      fov: 3
      hold_to_aim_key: ALT
      min_distance: null
      screen_size:
        height: 1080
        width: 1920
      toggle_keep_target: NUMPAD3
    dodge:
      crouch_Key: ctrl
      is_active: false
      toggle_key: NUMPAD2
    hunt:
      target_select: NUMPAD8
      toggle_key: NUMPAD5
  slow:
    aiming:
      falloff_correction:
        amount: 1.02
        decrease_key: SUBTRACT
        increase_key: ADD
      fixed_correction:
        amount: 1
        decrease_key: NUMPAD9
        increase_key: NUMPAD6
      locations:
        - HeadEnd
        - Head
        - Spine
        - Neck
        - Hips
      movement_prediction_factor:
        amount: 0.03
        decrease_key: PAGEDOWN
        increase_key: PAGEUP
        is_active: false
        toggle_key: MULTIPLY
      switch_location_key: END
    auto_scope:
      is_active: false
    auto_shoot:
      is_active: false
      toggle_key: NUMPAD1
    basic:
      fov: 3
      hold_to_aim_key: ALT
      min_distance: null
      screen_size:
        height: 1080
        width: 1920
      toggle_keep_target: NUMPAD3
    dodge:
      crouch_Key: ctrl
      is_active: false
      toggle_key: NUMPAD2
    hunt:
      target_select: NUMPAD8
      toggle_key: NUMPAD5
overlay:
  is_active: true
